name: Minify files and copy non-minified items

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g html-minifier-terser
        npm install -g clean-css-cli
        npm install -g terser

    - name: Minify HTML files
      run: |
        find original -type f -name "*.html" | while read file; do
          dir=$(dirname "${file#original/}")
          mkdir -p "$dir"
          html-minifier-terser "$file" -o "${file#original/}" --collapse-whitespace --remove-comments --minify-css true --minify-js true
        done
 
    - name: Minify CSS files
      run: |
        find original -type f -name "*.css" | while read file; do
          dir=$(dirname "${file#original/}")
          mkdir -p "$dir"
          cleancss -o "${file#original/}" "$file"
        done

    - name: Minify JS files
      run: |
        find original -type f -name "*.js" | while read file; do
          dir=$(dirname "${file#original/}")
          mkdir -p "$dir"
          terser "$file" -o "${file#original/}"
        done

    - name: Copy non-minified files and folders
      run: |
        find original -maxdepth 1 -mindepth 1 | while read item; do
          if [[ "$item" != *"/css" && "$item" != *"/html" && "$item" != *"/js" && "$item" != *"/test" && "$item" != *"/third" && "$item" != *"/index.html" ]]; then
            cp -r "$item" .
          fi
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Minify files and copy non-minified items from original directory' || echo "No changes to commit"
        git push