name: Minify and Restructure
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        npm install -g html-minifier-terser
        npm install -g clean-css-cli
        npm install -g terser
    - name: Clear parent directory
      run: |
        shopt -s extglob
        rm -rf !(original)
        echo "Parent directory cleared except for 'original' folder"
    - name: Copy directory structure
      run: |
        find original -type d | sed 's|^original/||' | xargs -I {} mkdir -p {}
        echo "Directory structure copied from 'original' to parent directory"
    - name: Minify HTML files
      run: |
        find original -type f -name "*.html" | while read file; do
          output_file="${file#original/}"
          echo "Minifying $file to $output_file"
          html-minifier-terser "$file" -o "$output_file" --collapse-whitespace --remove-comments --minify-css true --minify-js true
        done
    - name: Minify CSS files
      run: |
        find original -type f -name "*.css" | while read file; do
          output_file="${file#original/}"
          echo "Minifying $file to $output_file"
          cleancss -o "$output_file" "$file"
        done
    - name: Minify JS files
      run: |
        find original -type f -name "*.js" | while read file; do
          output_file="${file#original/}"
          echo "Minifying $file to $output_file"
          terser "$file" -o "$output_file"
        done
    - name: Copy non-minified files
      run: |
        find original -type f ! -name "*.html" ! -name "*.css" ! -name "*.js" | while read file; do
          output_file="${file#original/}"
          echo "Copying $file to $output_file"
          cp "$file" "$output_file"
        done
    - name: List files in root directory
      run: |
        echo "Contents of root directory after all operations:"
        ls -R
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Minify files and restructure from original directory' || echo "No changes to commit"
        git pull --rebase origin main
        git push